version: "0.5"

processes:
  mcp:
    command: uv run mcp dev ./mcp-server/main.py
  ollama:
    command: export OLLAMA_HOST=127.0.0.1:3000 && export OLLAMA_MODELS=/usr/share/ollama/.ollama/models && ollama serve
  n8n:
    command: n8n start
